galaxy_info:
  author: your name
  description: your description
  company: your company (optional)

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies:
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.  - role: modules-network
  - role: modules-network-a10
  - role: modules-network-aci
  - role: modules-network-aireos
  - role: modules-network-aos
  - role: modules-network-aruba
  - role: modules-network-asa
  - role: modules-network-avi
  - role: modules-network-bigswitch
  - role: modules-network-citrix
  - role: modules-network-cloudengine
  - role: modules-network-cloudvision
  - role: modules-network-cumulus
  - role: modules-network-dellos10
  - role: modules-network-dellos6
  - role: modules-network-dellos9
  - role: modules-network-eos
  - role: modules-network-f5
  - role: modules-network-fortios
  - role: modules-network-illumos
  - role: modules-network-interface
  - role: modules-network-ios
  - role: modules-network-iosxr
  - role: modules-network-junos
  - role: modules-network-layer2
  - role: modules-network-layer3
  - role: modules-network-lenovo
  - role: modules-network-netconf
  - role: modules-network-netscaler
  - role: modules-network-netvisor
  - role: modules-network-nuage
  - role: modules-network-nxos
  - role: modules-network-ordnance
  - role: modules-network-ovs
  - role: modules-network-panos
  - role: modules-network-protocol
  - role: modules-network-radware
  - role: modules-network-routing
  - role: modules-network-sros
  - role: modules-network-system
  - role: modules-network-vyos
