  - role: modules-cloud
  - role: modules-cloud-amazon
  - role: modules-cloud-atomic
  - role: modules-cloud-azure
  - role: modules-cloud-centurylink
  - role: modules-cloud-cloudscale
  - role: modules-cloud-cloudstack
  - role: modules-cloud-digital_ocean
  - role: modules-cloud-dimensiondata
  - role: modules-cloud-docker
  - role: modules-cloud-google
  - role: modules-cloud-linode
  - role: modules-cloud-lxc
  - role: modules-cloud-lxd
  - role: modules-cloud-misc
  - role: modules-cloud-openstack
  - role: modules-cloud-ovh
  - role: modules-cloud-ovirt
  - role: modules-cloud-packet
  - role: modules-cloud-profitbricks
  - role: modules-cloud-pubnub
  - role: modules-cloud-rackspace
  - role: modules-cloud-smartos
  - role: modules-cloud-softlayer
  - role: modules-cloud-univention
  - role: modules-cloud-vmware
  - role: modules-cloud-webfaction
